# Generated by Django 4.1.7 on 2023-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='ph',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
